/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseSwiper: typeof import('./../components/Base/SwiperTabs/BaseSwiper.vue')['default']
    Chart: typeof import('./../components/Chart/index.vue')['default']
    DefaultBtn: typeof import('./../components/Base/DefaultBtn.vue')['default']
    ESwiper: typeof import('./../components/Base/SwiperTabs/ESwiper.vue')['default']
    GhostButton: typeof import('./../components/GhostButton.vue')['default']
    HomeHeader: typeof import('./../components/Home/HomeHeader.vue')['default']
    HomeSideMenu: typeof import('./../components/Home/HomeSideMenu.vue')['default']
    LazyImage: typeof import('./../components/Base/LazyImage.vue')['default']
    NavBar: typeof import('./../components/Base/NavBar.vue')['default']
    PageContainer: typeof import('./../components/Base/PageContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollKeeper: typeof import('./../components/Base/ScrollKeeper.vue')['default']
    SideMenu: typeof import('./../components/SideMenu.vue')['default']
    SliderVerify: typeof import('./../components/SliderVerify.vue')['default']
    Swiper: typeof import('./../components/Base/SwiperTabs/Swiper.vue')['default']
    SwiperTabs: typeof import('./../components/Base/SwiperTabs/index.vue')['default']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    TopHeader: typeof import('./../components/TopHeader.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanRadio: typeof import('vant/es')['Radio']
    VanRadioGroup: typeof import('vant/es')['RadioGroup']
    VanSearch: typeof import('vant/es')['Search']
    VanSpace: typeof import('vant/es')['Space']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwitch: typeof import('vant/es')['Switch']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
