/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseSwiper: typeof import('./../components/Base/SwiperTabs/BaseSwiper.vue')['default']
    DefaultBtn: typeof import('./../components/Base/DefaultBtn.vue')['default']
    DemoDialog: typeof import('./../components/Modal/DemoDialog.vue')['default']
    DemoModal: typeof import('./../components/Modal/DemoModal.vue')['default']
    HomeHeader: typeof import('./../components/Home/HomeHeader.vue')['default']
    HomeSideMenu: typeof import('./../components/Home/HomeSideMenu.vue')['default']
    InstallPrompt: typeof import('./../components/PWA/InstallPrompt.vue')['default']
    LazyImage: typeof import('./../components/Base/LazyImage.vue')['default']
    NavBar: typeof import('./../components/Base/NavBar.vue')['default']
    PageContainer: typeof import('./../components/Base/PageContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderVerify: typeof import('./../components/SliderVerify.vue')['default']
    SwiperTabs: typeof import('./../components/Base/SwiperTabs/index.vue')['default']
    TabBar: typeof import('./../components/TabBar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanConfigProvider: typeof import('vant/es')['ConfigProvider']
    VanDialog: typeof import('vant/es')['Dialog']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPopup: typeof import('vant/es')['Popup']
    VanSticky: typeof import('vant/es')['Sticky']
    VanTab: typeof import('vant/es')['Tab']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTabs: typeof import('vant/es')['Tabs']
    VanTextEllipsis: typeof import('vant/es')['TextEllipsis']
  }
}
