/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import type {DefineComponent} from "vue";

export {}

declare module 'vue' {
  export interface GlobalComponents {
     LazyComponent: DefineComponent<NonNullable<unknown>, NonNullable<unknown>, any>

  }
}
