/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'index': RouteRecordInfo<'index', '/', Record<never, never>, Record<never, never>>,
    '404': RouteRecordInfo<'404', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    'demo': RouteRecordInfo<'demo', '/demo', Record<never, never>, Record<never, never>>,
    'lazy-image': RouteRecordInfo<'lazy-image', '/demo/Image', Record<never, never>, Record<never, never>>,
    'pull': RouteRecordInfo<'pull', '/demo/pull', Record<never, never>, Record<never, never>>,
    'demo-swiper': RouteRecordInfo<'demo-swiper', '/demo/swiper', Record<never, never>, Record<never, never>>,
    'Demo1': RouteRecordInfo<'Demo1', '/demo1', Record<never, never>, Record<never, never>>,
    'GameDetail': RouteRecordInfo<'GameDetail', '/game/:gameId', { gameId: ParamValue<true> }, { gameId: ParamValue<false> }>,
    'GameCategory': RouteRecordInfo<'GameCategory', '/game/category', Record<never, never>, Record<never, never>>,
    'Home': RouteRecordInfo<'Home', '/home', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'Profile': RouteRecordInfo<'Profile', '/profile', Record<never, never>, Record<never, never>>,
    'ScrollCache': RouteRecordInfo<'ScrollCache', '/scroll-cache', Record<never, never>, Record<never, never>>,
    'settings': RouteRecordInfo<'settings', '/settings', Record<never, never>, Record<never, never>>,
  }
}
